# This file intentionally left blank

BOOTLOADER = rp2040
BOARD = GENERIC_RP_RP2040
LTO_ENABLE = yes
CONSOLE_ENABLE=yes
OS_DETECTION_DEBUG_ENABLE = yes

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

AUDIO_ENABLE = no

ENCODER_ENABLE = yes

NKRO_ENABLE = yes
